#!/bin/bash
# backup-immich-glacier.sh - offsite copy of the Immich library to S3 Deep Archive
#
# Layout notes (verified 2026-08-04):
#   Storage template is OFF, so originals live in upload/<userID>/xx/yy/<uuid>.ext
#   with no date structure. Per-file rclone copy is used instead of tar; rclone
#   compares against the bucket itself, so no ledger is needed here.
#
#   thumbs/ and encoded-video/ are excluded - both are regenerated by Immich jobs.
#
#   The external library at /mnt/user/photoLibraries is covered separately by
#   backup-photos-glacier.sh. Neither set is restorable without the database:
#   Immich stores file paths in Postgres and never scans the filesystem.
#
# Ordering: the database dump is uploaded before the files. The dump is produced
# by Immich itself (nightly, into UPLOAD_LOCATION/backups), so it is always older
# than the files being uploaded. That is the safe direction - the worst case is
# files the database does not know about, which can be re-imported by hand.

set -uo pipefail

source /mnt/user/appdata/compose/scripts/.env

IMMICH_ROOT="/mnt/user/immich/photos"
LEDGER_DIR="/mnt/user/appdata/archive-ledger"
LOG="${LEDGER_DIR}/immich-backup.log"
DB_STAMP="${LEDGER_DIR}/.immich-db-last-upload"
APPRISE_URL="http://localhost:8001/notify/backup"
LOCK_FILE="/tmp/immich-glacier.lock"

# The dump is ~2 GB and Deep Archive has a 180-day minimum, so uploading one
# every weekly run would waste both space and money. One per month is enough:
# the database changes far more slowly than the asset set.
DB_INTERVAL_DAYS=90

# Fall back to sane values if .env is missing an entry
RCLONE_REMOTE="${RCLONE_REMOTE:-photos-crypt}"
BWLIMIT="${BWLIMIT:-5M}"

export RCLONE_CONFIG="/mnt/user/appdata/rclone-glacier/rclone.conf"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG"; }

notify() {
  curl -sf -X POST "$APPRISE_URL" \
    --data-urlencode "title=Immich Glacier Backup" \
    --data-urlencode "body=$1" > /dev/null 2>&1
}

# --- Lock ---
if [ -f "$LOCK_FILE" ]; then
  existing_pid=$(cat "$LOCK_FILE" 2>/dev/null)
  if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
    log "SKIP: already running (PID $existing_pid)"
    exit 0
  fi
  log "WARN: removing stale lock (PID ${existing_pid:-unknown})"
fi
mkdir -p "$LEDGER_DIR"
echo $$ > "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

log "=== Immich backup started (PID $$) ==="

# --- Preflight: fail before transferring anything ---
if ! rclone listremotes 2>/dev/null | grep -q "^${RCLONE_REMOTE}:"; then
  log "FATAL: rclone remote ${RCLONE_REMOTE} unavailable (config: $RCLONE_CONFIG)"
  notify "Aborted: rclone remote ${RCLONE_REMOTE} not found"
  exit 1
fi
for d in upload profile backups; do
  if [ ! -d "${IMMICH_ROOT}/${d}" ]; then
    log "FATAL: ${IMMICH_ROOT}/${d} not found"
    notify "Aborted: ${IMMICH_ROOT}/${d} missing"
    exit 1
  fi
done
log "Preflight OK: remote ${RCLONE_REMOTE}, root ${IMMICH_ROOT}"

ERRORS=0

# --- 1. Database dump, at most once per DB_INTERVAL_DAYS ---
DUMP=$(ls -t "${IMMICH_ROOT}/backups/"*.sql.gz 2>/dev/null | head -1)

if [ -z "$DUMP" ]; then
  log "FATAL: no database dump in ${IMMICH_ROOT}/backups/ - check Administration > Settings > Backup"
  notify "Aborted: no database dump available"
  exit 1
fi

DUMP_AGE_H=$(( ( $(date +%s) - $(stat -c %Y "$DUMP") ) / 3600 ))
if [ "$DUMP_AGE_H" -gt 48 ]; then
  log "WARN: newest dump is ${DUMP_AGE_H}h old - the Immich backup job may be broken"
  notify "WARNING: newest Immich database dump is ${DUMP_AGE_H}h old"
fi

UPLOAD_DB=1
if [ -f "$DB_STAMP" ]; then
  STAMP_AGE_D=$(( ( $(date +%s) - $(stat -c %Y "$DB_STAMP") ) / 86400 ))
  if [ "$STAMP_AGE_D" -lt "$DB_INTERVAL_DAYS" ]; then
    UPLOAD_DB=0
    log "Database dump skipped: last upload was ${STAMP_AGE_D}d ago (interval ${DB_INTERVAL_DAYS}d)"
  fi
fi

if [ "$UPLOAD_DB" -eq 1 ]; then
  log "Uploading database dump: $(basename "$DUMP") (${DUMP_AGE_H}h old, $(du -h "$DUMP" | cut -f1))"
  if rclone copy "$DUMP" "${RCLONE_REMOTE}:immich/db/" \
       --s3-storage-class DEEP_ARCHIVE \
       --bwlimit "$BWLIMIT" \
       --log-file "$LOG" --log-level INFO; then
    touch "$DB_STAMP"
    log "OK: database dump uploaded"
  else
    log "ERROR: database dump upload failed"
    ERRORS=$((ERRORS + 1))
  fi
fi

# --- 2. Original assets and profile images ---
# copy, never sync: deleting an asset in Immich must not delete the archived copy.
# --size-only: Deep Archive objects cannot be read back, and crypt filenames are
# deterministic, so size comparison is both sufficient and cheap.
for d in upload profile; do
  log "Syncing ${d}/"
  if rclone copy "${IMMICH_ROOT}/${d}" "${RCLONE_REMOTE}:immich/${d}" \
       --s3-storage-class DEEP_ARCHIVE \
       --bwlimit "$BWLIMIT" \
       --transfers 4 \
       --size-only \
       --stats-one-line \
       --log-file "$LOG" --log-level INFO; then
    log "OK: ${d}/ synced"
  else
    log "ERROR: ${d}/ sync failed"
    ERRORS=$((ERRORS + 1))
  fi
done

# --- 3. Report ---
LOCAL_FILES=$(find "${IMMICH_ROOT}/upload" -type f | wc -l)
REMOTE_FILES=$(rclone ls "${RCLONE_REMOTE}:immich/upload" 2>/dev/null | wc -l)
REMOTE_SIZE=$(rclone size "${RCLONE_REMOTE}:immich/" 2>/dev/null | tr '\n' ' ')

log "Files: ${LOCAL_FILES} local, ${REMOTE_FILES} remote"
log "Remote: ${REMOTE_SIZE}"

if [ "$REMOTE_FILES" -lt "$LOCAL_FILES" ]; then
  log "WARN: remote has fewer files than local - transfer may be incomplete"
fi

if [ "$ERRORS" -eq 0 ]; then
  notify "Immich backup OK
files: ${REMOTE_FILES} remote / ${LOCAL_FILES} local
${REMOTE_SIZE}"
  log "=== Completed without errors ==="
else
  notify "ERROR: $ERRORS failure(s) - check $LOG"
  log "=== Completed with errors: $ERRORS ==="
  exit 1
fi
