services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma-local
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /mnt/user/appdata/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Moscow
