services:
  apprise-api:
    container_name: apprise-api
    image: lscr.io/linuxserver/apprise-api:1.3.1
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Berlin
      - APPRISE_ATTACH_SIZE=25
    volumes:
      - /mnt/user/appdata/apprise-api/config:/config
      - /mnt/user/appdata/apprise-api/attach:/attachments
    ports:
      - "8001:8000"